version: '3.6'

services:

  pg:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      # This may be useful during development to access the database directly.
      - 5433:5432


  pg-create-users:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=$POSTGRES_PASSWORD
    command:
      psql -h pg -d "$POSTGRES_DB" -U "$POSTGRES_USER" -f /docker-entrypoint-initdb.d/create-users.sql
    depends_on:
      - pg
    restart: on-failure


  identity-provider:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=4488
    image: oryd/hydra-login-consent-node:$HYDRA_VERSION
    ports:
      # This is the public endpoint for login and consent pages.
      - 4488:4488


  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
    command:
      migrate sql postgres://hydra_service:hydra_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    ports:
      # This is the public Oauth2 endpoint.
      - 4444:4444
      # This may be useful during development to access the admin API.
      - 4445:4445
    depends_on:
      - hydra-migrate
    command:
      serve all --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
      - DATABASE_URL=postgres://hydra_service:hydra_service@pg/${POSTGRES_DB}?sslmode=disable
      - OAUTH2_CONSENT_URL=http://$BROWSER_IDP_HOST:4488/consent
      - OAUTH2_LOGIN_URL=http://$BROWSER_IDP_HOST:4488/login
      - OAUTH2_ISSUER_URL=http://$BROWSER_HYDRA_HOST:4444
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - HYDRA_ADMIN_URL=http://hydra:4445
    depends_on:
      - pg
      - identity-provider


  keto-migrate:
    image: oryd/keto:$KETO_VERSION
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://keto_service:keto_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  keto:
    image: oryd/keto:$KETO_VERSION
    ports:
      # This may be useful during development to access the admin API.
      - 4466:4466
    depends_on:
      - keto-migrate
      - hydra
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - DATABASE_URL=postgres://keto_service:keto_service@pg/${POSTGRES_DB}?sslmode=disable
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect


  oathkeeper-migrate:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://oathkeeper_service:oathkeeper_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  oathkeeper-api:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    ports:
      # This may be useful during development to access the admin API.
      - 4456:4456
    depends_on:
      - oathkeeper-migrate
      - hydra
      - keto
    command:
      serve api
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - PORT=4456
      - DATABASE_URL=postgres://oathkeeper_service:oathkeeper_service@pg/${POSTGRES_DB}?sslmode=disable
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token


  oathkeeper-proxy:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    ports:
      # This is the public entrypoint for all APIs.
      - 4455:4455
    depends_on:
      - oathkeeper-api
    command:
      serve proxy
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - PORT=4455
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token


  oauth2-config:
    build:
      context: ./services/oauth2-config
      dockerfile: Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
        - KETO_VERSION=$KETO_VERSION
        - OATHKEEPER_VERSION=$OATHKEEPER_VERSION
    depends_on:
      - hydra
      - keto
      - oathkeeper-api
    environment:
      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KETO_URL=http://keto:4466
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - OATHKEEPER_PROXY_URL=http://oathkeeper-proxy:4455
      - BROWSER_API_PROXY_URL=$BROWSER_API_PROXY_URL
      - RESOURCE_SERVER_URL=http://users:10001

      # This sets the prefix for all resource, action, and subject names. Be aware that this prefix is automatically
      # applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=subjects:hydra:"
      - "HYDRA_RESOURCE_PREFIX=resources:hydra:"
      - "HYDRA_ACTION_PREFIX=actions:hydra:"
      - "OATHKEEPER_RESOURCE_PREFIX=resources:oathkeeper:"
      - "OATHKEEPER_ACTION_PREFIX=actions:oathkeeper:"
      - "KETO_RESOURCE_PREFIX=resources:keto:"
      - "KETO_ACTION_PREFIX=actions:keto:"

      - OATHKEEPER_HYDRA_JWK_SET_ID=jwk:oathkeeper
      - OATHKEEPER_HYDRA_CLIENT_ID=clients:oathkeeper
      - OATHKEEPER_HYDRA_CLIENT_SECRET=dummy-oathkeeper-secret
      - KETO_HYDRA_CLIENT_ID=clients:keto
      - KETO_HYDRA_CLIENT_SECRET=dummy-keto-secret


  redis-users:
    image: redis
    ports:
      # This may be useful during development to access the DB.
      - 6379:6379


  mail:
    image: mailhog/mailhog
    ports:
      # This may be useful during development to send and read emails.
      - 1025:1025
      - 8025:8025


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
      args:
        - FLASK_APP=users
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 10001:10001
    environment:
      - PORT=10001
      - SQLALCHEMY_DATABASE_URI=postgresql://users_service:users_service@pg/${POSTGRES_DB}
      - REDIS_URL=redis://redis-users:6379/0
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - pg
      - redis-users
      - mail


volumes:
  pg-data-volume:
