version: '3.6'

services:

  postgres:
    image: postgres:10.4
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    deploy:
      mode: global


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 5001:80
    environment:
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - postgres


volumes:
  pg-data-volume:
