version: '3.6'

services:

  pg:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432


  pg-create-users:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=$POSTGRES_PASSWORD
    command:
      psql -h pg -d "$POSTGRES_DB" -U "$POSTGRES_USER" -f /docker-entrypoint-initdb.d/create-users.sql
    depends_on:
      - pg
    restart: on-failure


  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
    command:
      migrate sql postgres://hydra_service:hydra_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  oathkeeper-migrate:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://oathkeeper_service:oathkeeper_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 10001:10001
    hostname: users_service
    environment:
      - PORT=10001
      - SQLALCHEMY_DATABASE_URI=postgresql://users_service:users_service@pg/${POSTGRES_DB}
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - pg


volumes:
  pg-data-volume:
