version: '3.6'

services:

  users-mongo:
    build:
      context: ./services/users
      dockerfile: Dockerfile-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - users-data-volume:/data/db

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-flask
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=users.py
      - FLASK_ENV=development
      # - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - users-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: users-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - users-mongo

volumes:
  users-data-volume:
