version: '3.6'

services:

  pg:
    image: postgres:10.4
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=swaptacular
      - POSTGRES_PASSWORD=mysecretpassword
    deploy:
      mode: global


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 5001:80
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:mysecretpassword@pg/swaptacular
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - pg


volumes:
  pg-data-volume:
