version: '3.6'

services:

  pg:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432


  pg-create-users:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=$POSTGRES_PASSWORD
    command:
      psql -h pg -d "$POSTGRES_DB" -U "$POSTGRES_USER" -f /docker-entrypoint-initdb.d/create-users.sql
    depends_on:
      - pg
    restart: on-failure


  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
    command:
      migrate sql postgres://hydra_service:hydra_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  oathkeeper-migrate:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://oathkeeper_service:oathkeeper_service@pg/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - pg
    restart: on-failure


  identity-provider:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=4488
    image: oryd/hydra-login-consent-node:$HYDRA_VERSION
    ports:
      - 4488:4488


  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    ports:
      - 4444:4444
      - 4445:4445
    depends_on:
      - hydra-migrate
    command:
      serve all --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
      - DATABASE_URL=postgres://hydra_service:hydra_service@pg/${POSTGRES_DB}?sslmode=disable
      - OAUTH2_CONSENT_URL=http://$BROWSER_IDP_HOST:4488/consent
      - OAUTH2_LOGIN_URL=http://$BROWSER_IDP_HOST:4488/login
      - OAUTH2_ISSUER_URL=http://$BROWSER_HYDRA_HOST:4444
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - HYDRA_ADMIN_URL=http://hydra:4445
    depends_on:
      - pg
      - identity-provider
    volumes:
      - './services/hydra/clients:/clients'


  oathkeeper-proxy:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    ports:
      - 4455:4455
    depends_on:
      - oathkeeper-api
      - hydra
    command:
      serve proxy
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - PORT=4455
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token


  oathkeeper-api:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    ports:
      - 4456:4456
    depends_on:
      - oathkeeper-migrate
    command:
      serve api
    environment:
      - LOG_LEVEL=debug
      - DISABLE_TELEMETRY=1
      - PORT=4456
      - DATABASE_URL=postgres://oathkeeper_service:oathkeeper_service@pg/${POSTGRES_DB}?sslmode=disable
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 10001:10001
    hostname: users_service
    environment:
      - PORT=10001
      - SQLALCHEMY_DATABASE_URI=postgresql://users_service:users_service@pg/${POSTGRES_DB}
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - pg


volumes:
  pg-data-volume:
