version: '3.6'

volumes:
  letsencrypt:


services:

  nginx:
    image: epandurski/docker-nginx-certbot:$NGINX_CERTBOT_VERSION
    volumes:
      - './docker/nginx/templates/default.conf.template:/etc/nginx/user.conf.d/default.conf:ro'
      - './docker/nginx/templates/proxy_cache_path.conf.template:/etc/nginx/user.conf.d/proxy_cache_path.conf:ro'
      - 'letsencrypt:/etc/letsencrypt'
    ports:
      - 80:80
    environment:
      CERTIFICATE_FILE: '/etc/letsencrypt/live/${PUBLIC_HOST}/fullchain.pem'
      CERTIFICATE_KEY_FILE: '/etc/letsencrypt/live/${PUBLIC_HOST}/privkey.pem'
      ENVSUBST_VARS: 'PORT
           CREDITORS_HYDRA_URL CREDITORS_LOGIN_URL CREDITORS_SERVER_URL CREDITORS_WEBAPP_URL CREDITORS_SWAGGER_UI_URL
           DEBTORS_HYDRA_URL DEBTORS_LOGIN_URL DEBTORS_SERVER_URL DEBTORS_WEBAPP_URL DEBTORS_SWAGGER_UI_URL
           CERTIFICATE_FILE CERTIFICATE_KEY_FILE CACHE_KEYS_ZONE CACHE_MAX_SIZE'
      CERTBOT_EMAIL: $CERTBOT_EMAIL
