version: '3.6'

services:

  pg:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    deploy:
      mode: global


  users:
    build:
      context: ./services/users
      dockerfile: docker-flask/Dockerfile
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 5001:80
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://users_service:users_service@pg/postgres
      - MESSAGE=Hello, Developer
    command: develop
    depends_on:
      - pg


volumes:
  pg-data-volume:
