version: '3.6'

services:

  users-mongo:
    build:
      context: ./services/users
      dockerfile: Dockerfile-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - users-data-volume:/data/db

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-flask
    volumes:
      - './services/users/src:/usr/src/app'
    ports:
      - 5001:80
    environment:
      - PYTHONDONTWRITEBYTECODE=true
      - FLASK_ENV=development
      - GUNICORN_ACCESSLOG=-
      - GUNICORN_WORKERS=1
      - GUNICORN_THREADS=1
      # - APP_SETTINGS=project.config.DevelopmentConfig
    command: python -m flask run -h 0.0.0.0 --port 80
    depends_on:
      - users-mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: users-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - users-mongo

volumes:
  users-data-volume:
