# These variables must be set before running the `configure.sh`
# script. They can be set in this file directly or, even better,
# during the operating system start.

export PUBLIC_HOST=$PUBLIC_HOST
export PUBLIC_PORT=$PUBLIC_PORT
export MIN_CREDITOR_ID=$MIN_CREDITOR_ID
export MAX_CREDITOR_ID=$MAX_CREDITOR_ID
export MIN_DEBTOR_ID=$MIN_DEBTOR_ID
export MAX_DEBTOR_ID=$MAX_DEBTOR_ID
export MAIL_SERVER_HOSTNAME=$MAIL_SERVER_HOSTNAME
export SMTP_SERVER=$SMTP_SERVER
export SMTP_PORT=$SMTP_PORT
export SMTP_USERNAME=$SMTP_USERNAME
export SMTP_PASSWORD=$SMTP_PASSWORD
export RECAPTCHA_PUBLIC_KEY=$RECAPTCHA_PUBLIC_KEY
export RECAPTCHA_PIVATE_KEY=$RECAPTCHA_PIVATE_KEY
export CREDITORS_SUPERVISOR_CLIENT_SECRET=$CREDITORS_SUPERVISOR_CLIENT_SECRET
export CREDITORS_PIN_PROTECTION_SECRET=$CREDITORS_PIN_PROTECTION_SECRET
export CREDITORS_LOGIN_COOKIE_SECRET=$CREDITORS_LOGIN_COOKIE_SECRET
export CREDITORS_LOGIN_SYSTEM_SECRET=$CREDITORS_LOGIN_SYSTEM_SECRET
export DEBTORS_SUPERVISOR_CLIENT_SECRET=$DEBTORS_SUPERVISOR_CLIENT_SECRET
export DEBTORS_LOGIN_COOKIE_SECRET=$DEBTORS_LOGIN_COOKIE_SECRET
export DEBTORS_LOGIN_SYSTEM_SECRET=$DEBTORS_LOGIN_SYSTEM_SECRET
