# These variables must be set before running the `configure.sh`
# script. They can be set in this file directly or, even better,
# during the operating system start.

export PUBLIC_HOST=$PUBLIC_HOST
export PUBLIC_PORT=$PUBLIC_PORT
export MIN_CREDITOR_ID=$MIN_CREDITOR_ID
export MAX_CREDITOR_ID=$MAX_CREDITOR_ID
export MIN_DEBTOR_ID=$MIN_DEBTOR_ID
export MAX_DEBTOR_ID=$MAX_DEBTOR_ID
export RECAPTCHA_PUBLIC_KEY=$RECAPTCHA_PUBLIC_KEY
export RECAPTCHA_PIVATE_KEY=$RECAPTCHA_PIVATE_KEY
export CREDITORS_SUPERVISOR_CLIENT_SECRET=$CREDITORS_SUPERVISOR_CLIENT_SECRET
export CREDITORS_PIN_PROTECTION_SECRET=$CREDITORS_PIN_PROTECTION_SECRET
export CREDITORS_LOGIN_COOKIE_SECRET=$CREDITORS_LOGIN_COOKIE_SECRET
export CREDITORS_LOGIN_SYSTEM_SECRET=$CREDITORS_LOGIN_SYSTEM_SECRET
export DEBTORS_SUPERVISOR_CLIENT_SECRET=$DEBTORS_SUPERVISOR_CLIENT_SECRET
export DEBTORS_LOGIN_COOKIE_SECRET=$DEBTORS_LOGIN_COOKIE_SECRET
export DEBTORS_LOGIN_SYSTEM_SECRET=$DEBTORS_LOGIN_SYSTEM_SECRET


# DO NOT COMMIT THIS:
export PUBLIC_HOST=localhost:44301
export PUBLIC_PORT=44301
export MIN_CREDITOR_ID=4294967296
export MAX_CREDITOR_ID=8589934591
export MIN_DEBTOR_ID=4294967296
export MAX_DEBTOR_ID=8589934591
export RECAPTCHA_PUBLIC_KEY=6Lc902MUAAAAAJL22lcbpY3fvg3j4LSERDDQYe37
export RECAPTCHA_PIVATE_KEY=6Lc902MUAAAAAN--r4vUr8Vr7MU1PF16D9k2Ds9Q
export CREDITORS_SUPERVISOR_CLIENT_SECRET=creditors-supervisor
export CREDITORS_PIN_PROTECTION_SECRET=some-long-string-that-must-be-kept-secret
export CREDITORS_LOGIN_COOKIE_SECRET=some-long-string-that-must-be-kept-secret
export CREDITORS_LOGIN_SYSTEM_SECRET=some-long-string-that-must-be-kept-secret
export DEBTORS_SUPERVISOR_CLIENT_SECRET=debtors-supervisor
export DEBTORS_LOGIN_COOKIE_SECRET=some-long-string-that-must-be-kept-secret
export DEBTORS_LOGIN_SYSTEM_SECRET=some-long-string-that-must-be-kept-secret
