# These variables must be set before running the `configure.sh`
# script. They can be set in this file directly or, even better,
# during the operating system start.

export PUBLIC_HOST=$PUBLIC_HOST
export PUBLIC_PORT=$PUBLIC_PORT
export RECAPTCHA_PUBLIC_KEY=$RECAPTCHA_PUBLIC_KEY
export RECAPTCHA_PIVATE_KEY=$RECAPTCHA_PIVATE_KEY
export CREDITORS_SUPERVISOR_CLIENT_SECRET=$CREDITORS_SUPERVISOR_CLIENT_SECRET
export CREDITORS_PIN_PROTECTION_SECRET=$CREDITORS_PIN_PROTECTION_SECRET
export CREDITORS_LOGIN_COOKIE_SECRET=$CREDITORS_LOGIN_COOKIE_SECRET
export CREDITORS_LOGIN_SYSTEM_SECRET=$CREDITORS_LOGIN_SYSTEM_SECRET
export DEBTORS_SUPERVISOR_CLIENT_SECRET=$DEBTORS_SUPERVISOR_CLIENT_SECRET
export DEBTORS_LOGIN_COOKIE_SECRET=$DEBTORS_LOGIN_COOKIE_SECRET
export DEBTORS_LOGIN_SYSTEM_SECRET=$DEBTORS_LOGIN_SYSTEM_SECRET
