"""empty message

Revision ID: 8362f8cde2ed
Revises: 2883a2acf361
Create Date: 2018-09-17 14:33:57.471742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8362f8cde2ed'
down_revision = '2883a2acf361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('password_salt', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('recovery_code_hash', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'recovery_code_hash')
    op.drop_column('user', 'password_salt')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
