- id: "${OATHKEEPER_RESOURCE_PREFIX}rules:users"
  upstream:
    url: "${RESOURCE_SERVER_URL}/"
  match:
    url: "${BROWSER_API_PROXY_URL}/users/<.*>"
    methods:
      - GET
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope:
          - scope-a
          - scope-b
    - handler: anonymous
  authorizer:
    handler: allow
  credentials_issuer:
    handler: headers
    config:
      headers:
        X-User: "{{ print .Subject }}"
