# base image
FROM python:3.5.3-alpine

# set working directory
WORKDIR /usr/src/app

# add and install requirements
ADD Pipfile* ./
RUN pip install pipenv
RUN pipenv install

# add app
ADD users.py .

# run server
CMD pipenv run python -m flask run -h 0.0.0.0
