"""empty message

Revision ID: 280cfe9d1c7e
Revises: 73b98890e8e5
Create Date: 2018-11-12 14:10:54.585465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280cfe9d1c7e'
down_revision = '73b98890e8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_update_signal', 'new_email', new_column_name='email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_update_signal', sa.Column('new_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_update_signal', 'email')
    # ### end Alembic commands ###
