"""empty message

Revision ID: 610f027cd7b0
Revises: 4e8ccab26b34
Create Date: 2018-10-01 12:33:50.479006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610f027cd7b0'
down_revision = '4e8ccab26b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('two_factor_login', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET two_factor_login=TRUE')
    op.alter_column('user', 'two_factor_login', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'two_factor_login')
    # ### end Alembic commands ###
