"""empty message

Revision ID: fdefad17cc6e
Revises: d8ea3824a502
Create Date: 2018-10-22 16:26:57.236534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdefad17cc6e'
down_revision = 'd8ea3824a502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_update_signal',
    sa.Column('user_update_signal_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('old_email', sa.Text(), nullable=True),
    sa.Column('new_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_update_signal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_update_signal')
    # ### end Alembic commands ###
